spring.application.name=expence-tracker

# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate / JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true