CREATE TABLE roles (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)    NOT NULL,

    CONSTRAINT pk_roles         PRIMARY KEY (id),
    CONSTRAINT uk_roles_name    UNIQUE (name)
);

CREATE INDEX idx_roles_name ON roles (name);

CREATE TABLE capabilities (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)    NOT NULL,
    description VARCHAR(255)    NULL,

    CONSTRAINT  pk_capabilities      PRIMARY KEY (id),
    CONSTRAINT  uk_capabilities_name UNIQUE (name)
);

CREATE INDEX idx_capabilities_name ON capabilities (name);

CREATE TABLE roles_capabilities (
    role_id       BIGINT        NOT NULL,
    capability_id BIGINT        NOT NULL,

    CONSTRAINT pk_roles_capabilities PRIMARY KEY (role_id, capability_id),
    CONSTRAINT fk_roles_capabilities_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_roles_capabilities_capability
        FOREIGN KEY (capability_id) REFERENCES capabilities (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_roles_capabilities_capability_id ON roles_capabilities (capability_id);

CREATE TABLE users (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID            NOT NULL,
    email       VARCHAR(255)    NOT NULL,
    display_name VARCHAR(21)    NOT NULL,
    password    VARCHAR(255)    NOT NULL,
    role_id     BIGINT          NOT NULL,
    created_at  TIMESTAMPTZ     NOT NULL,
    updated_at  TIMESTAMPTZ     NOT NULL,
    deleted     BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ     NULL,

    CONSTRAINT pk_users             PRIMARY KEY (id),
    CONSTRAINT uk_users_uuid        UNIQUE (uuid),
    CONSTRAINT uk_users_email       UNIQUE (email),
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE RESTRICT
);

CREATE INDEX ix_users_role_id   ON users (role_id);
CREATE INDEX ix_users_deleted ON users (deleted) WHERE deleted = false;

CREATE TABLE accounts (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID            NOT NULL,
    name                VARCHAR(50)     NOT NULL,
    balance             DECIMAL(19,4)   NOT NULL,
    account_type        VARCHAR(50)     NOT NULL,
    default_account     BOOLEAN         NOT NULL DEFAULT FALSE,
    user_id             BIGINT          NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL,
    updated_at          TIMESTAMPTZ     NOT NULL,
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ     NULL,

    CONSTRAINT pk_accounts              PRIMARY KEY (id),
    CONSTRAINT uk_accounts_uuid         UNIQUE (uuid),
    CONSTRAINT uk_accounts_name_user    UNIQUE (name, user_id),
    CONSTRAINT fk_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE RESTRICT
);

CREATE INDEX ix_accounts_deleted ON accounts (deleted) WHERE deleted = false;
CREATE INDEX ix_accounts_user_id ON accounts (user_id);

CREATE TABLE categories (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID            NOT NULL,
    name                VARCHAR(50)     NOT NULL,
    transaction_type    VARCHAR(50)     NOT NULL,
    user_id             BIGINT          NOT NULL,
    parent_id           BIGINT                  ,
    created_at          TIMESTAMPTZ     NOT NULL,
    updated_at          TIMESTAMPTZ     NOT NULL,
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ     NULL,

    CONSTRAINT pk_categories            PRIMARY KEY (id),
    CONSTRAINT uk_categories_uuid       UNIQUE (uuid),
    CONSTRAINT fk_categories_user
                        FOREIGN KEY (user_id) REFERENCES users (id)
                        ON DELETE RESTRICT,
    CONSTRAINT fk_categories_parent
                        FOREIGN KEY (parent_id) REFERENCES categories (id)
                        ON DELETE RESTRICT
);

CREATE INDEX ix_categories_deleted ON categories (deleted) WHERE deleted = false;
CREATE INDEX ix_categories_user_id ON categories (user_id);

CREATE TABLE transactions (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID            NOT NULL,
    transaction_date    DATE            NOT NULL,
    transaction_type    VARCHAR(50)     NOT NULL,
    amount              DECIMAL(19,4)   NOT NULL,
    description         VARCHAR(255)            ,
    user_id             BIGINT          NOT NULL,
    source_account_id   BIGINT          NOT NULL,
    target_account_id   BIGINT                  ,
    category_id         BIGINT                  ,
    created_at          TIMESTAMPTZ     NOT NULL,
    updated_at          TIMESTAMPTZ     NOT NULL,
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ     NULL,

    CONSTRAINT pk_transactions          PRIMARY KEY (id),
    CONSTRAINT uk_transactions_uuid     UNIQUE (uuid),
    CONSTRAINT fk_transactions_user
                                        FOREIGN KEY (user_id) REFERENCES users (id)
                                        ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_source_account
                                        FOREIGN KEY (source_account_id) REFERENCES accounts (id)
                                        ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_target_account
                                        FOREIGN KEY (target_account_id) REFERENCES accounts (id)
                                        ON DELETE RESTRICT,
    CONSTRAINT fk_transactions_category
                                        FOREIGN KEY (category_id) REFERENCES categories (id)
                                        ON DELETE RESTRICT,
    CONSTRAINT chk_transaction_category_required
                                        CHECK (transaction_type = 'TRANSFER' OR category_id IS NOT NULL)
);

CREATE UNIQUE INDEX uk_categories_name_user_type_parent_null
    ON categories (name, user_id, transaction_type, parent_id) WHERE parent_id IS NULL;
CREATE UNIQUE INDEX uk_categories_name_user_type_parent_not_null
    ON categories (name, user_id, transaction_type, parent_id) WHERE parent_id IS NOT NULL;

CREATE INDEX ix_transactions_deleted ON transactions (deleted) WHERE deleted = false;
CREATE INDEX ix_transactions_category_id ON transactions (category_id);
CREATE INDEX ix_transactions_transaction_type ON transactions (transaction_type);
CREATE INDEX ix_transactions_transaction_date ON transactions (transaction_date);
CREATE INDEX ix_transactions_source_account_id ON transactions (source_account_id);
CREATE INDEX ix_transactions_target_account_id ON transactions (target_account_id);