CREATE TABLE users (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID            NOT NULL,
    email       VARCHAR(255)    NOT NULL,
    username    VARCHAR(50)     NOT NULL,
    password    VARCHAR(255)    NOT NULL,
    active      BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ     NOT NULL,
    updated_at  TIMESTAMPTZ     NOT NULL,
    deleted     BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ     NULL,

    CONSTRAINT pk_users             PRIMARY KEY (id),
    CONSTRAINT uk_users_uuid        UNIQUE (uuid),
    CONSTRAINT uk_users_email       UNIQUE (email),
    CONSTRAINT uk_users_username    UNIQUE (username)
);

CREATE INDEX ix_users_deleted ON users (deleted) WHERE deleted = false;

CREATE TABLE accounts (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID            NOT NULL,
    name                VARCHAR(50)     NOT NULL,
    balance             DECIMAL(19,4)   NOT NULL,
    account_type        VARCHAR(50)     NOT NULL,
    default_account     BOOLEAN         NOT NULL DEFAULT FALSE,
    user_id             BIGINT          NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL,
    updated_at          TIMESTAMPTZ     NOT NULL,
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ     NULL,

    CONSTRAINT pk_accounts              PRIMARY KEY (id),
    CONSTRAINT uk_accounts_uuid         UNIQUE (uuid),
    CONSTRAINT uk_accounts_name_user    UNIQUE (name, user_id),
    CONSTRAINT fk_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE RESTRICT
);

CREATE INDEX ix_accounts_deleted ON accounts (deleted) WHERE deleted = false;
CREATE INDEX ix_accounts_user_id ON accounts (user_id);

CREATE TABLE categories (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid                UUID            NOT NULL,
    name                VARCHAR(50)     NOT NULL,
    transaction_type    VARCHAR(50)     NOT NULL,
    user_id             BIGINT          NOT NULL,
    parent_id           BIGINT                  ,
    created_at          TIMESTAMPTZ     NOT NULL,
    updated_at          TIMESTAMPTZ     NOT NULL,
    deleted             BOOLEAN         NOT NULL DEFAULT FALSE,
    deleted_at          TIMESTAMPTZ     NULL,

    CONSTRAINT pk_categories            PRIMARY KEY (id),
    CONSTRAINT uk_categories_uuid       UNIQUE (uuid),
    CONSTRAINT uk_categories_name_user  UNIQUE (name, user_id),
    CONSTRAINT fk_categories_user
                        FOREIGN KEY (user_id) REFERENCES users (id)
                        ON DELETE RESTRICT
);

CREATE INDEX ix_categories_deleted ON categories (deleted) WHERE deleted = false;
CREATE INDEX ix_categories_user_id ON categories (user_id);